"""initial schema (postgres)

Revision ID: b69e2a2420de
Revises: 
Create Date: 2026-08-12 02:07:24.191057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b69e2a2420de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bot_persona', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.JSON(), nullable=False),
    sa.Column('target_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.Column('bot_tone_preference', sa.String(length=50), nullable=False),
    sa.Column('default_session_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_clerk_user_id'), 'students', ['clerk_user_id'], unique=True)
    op.create_table('cefr_promotion_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('previous_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.Column('new_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.Column('metrics_used', sa.JSON(), nullable=False),
    sa.Column('rule_applied', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cefr_promotion_log_student_id'), 'cefr_promotion_log', ['student_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.Enum('TEXT', 'VOICE', name='sessionmodality', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='sessionstatus', native_enum=False, length=15), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_student_id'), 'sessions', ['student_id'], unique=False)
    op.create_table('spaced_repetition_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('current_interval_days', sa.Integer(), nullable=False),
    sa.Column('correct_streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaced_repetition_cards_student_id'), 'spaced_repetition_cards', ['student_id'], unique=False)
    op.create_table('tool_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('has_free_alternative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_recommendations_student_id'), 'tool_recommendations', ['student_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.Enum('SENTENCE_COMPLETION', 'MULTIPLE_CHOICE', 'REFORMULATION', 'SHADOWING', name='exercisetype', native_enum=False, length=30), nullable=False),
    sa.Column('target_item', sa.String(length=255), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempts_session_id'), 'exercise_attempts', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Enum('STUDENT', 'BOT', name='messageauthor', native_enum=False, length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=1024), nullable=True),
    sa.Column('recast_corrections', sa.JSON(), nullable=True),
    sa.Column('pronunciation_scores', sa.JSON(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_vocabulary_count', sa.Integer(), nullable=False),
    sa.Column('grammar_errors_per_100_words', sa.Float(), nullable=False),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('avg_syntactic_complexity', sa.Float(), nullable=False),
    sa.Column('estimated_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefrlevel', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_student_id'), 'metric_snapshots', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshots_student_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_exercise_attempts_session_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_tool_recommendations_student_id'), table_name='tool_recommendations')
    op.drop_table('tool_recommendations')
    op.drop_index(op.f('ix_spaced_repetition_cards_student_id'), table_name='spaced_repetition_cards')
    op.drop_table('spaced_repetition_cards')
    op.drop_index(op.f('ix_sessions_student_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_cefr_promotion_log_student_id'), table_name='cefr_promotion_log')
    op.drop_table('cefr_promotion_log')
    op.drop_index(op.f('ix_students_clerk_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
